# Example GitHub Actions workflow for E2E tests
# Copy this to .github/workflows/e2e-tests.yml in your repository

name: Playwright E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'src/web/package-lock.json'

    - name: Install dependencies
      working-directory: ./src/web
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: ./src/web
      run: npx playwright install --with-deps ${{ matrix.browser }}

    - name: Run Playwright tests
      working-directory: ./src/web
      run: npx playwright test --project=${{ matrix.browser }}
      env:
        CI: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: src/web/tests/playwright-report/
        retention-days: 30

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-${{ matrix.browser }}-${{ github.run_number }}
        path: src/web/tests/screenshots/
        retention-days: 30

    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: videos-${{ matrix.browser }}-${{ github.run_number }}
        path: src/web/test-results/
        retention-days: 7

  smoke-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'src/web/package-lock.json'

    - name: Install dependencies
      working-directory: ./src/web
      run: npm ci

    - name: Install Playwright Browsers (Chromium only)
      working-directory: ./src/web
      run: npx playwright install --with-deps chromium

    - name: Run smoke tests
      working-directory: ./src/web
      run: npx playwright test smoke.spec.ts --project=chromium
      env:
        CI: true

    - name: Upload smoke test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: smoke-test-results
        path: src/web/tests/screenshots/smoke-*.png
        retention-days: 7

  mobile-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'src/web/package-lock.json'

    - name: Install dependencies
      working-directory: ./src/web
      run: npm ci

    - name: Install Playwright Browsers (Mobile)
      working-directory: ./src/web
      run: npx playwright install --with-deps chromium webkit

    - name: Run mobile tests
      working-directory: ./src/web
      run: npx playwright test responsive.spec.ts --project="Mobile Chrome" --project="Mobile Safari"
      env:
        CI: true

    - name: Upload mobile test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mobile-test-results
        path: src/web/tests/playwright-report/
        retention-days: 30

  visual-regression:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'src/web/package-lock.json'

    - name: Install dependencies
      working-directory: ./src/web
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: ./src/web
      run: npx playwright install --with-deps chromium

    - name: Run visual regression tests
      working-directory: ./src/web
      run: npx playwright test sections.spec.ts --project=chromium --grep "visual snapshot"
      env:
        CI: true

    - name: Upload visual regression results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: visual-regression-diff
        path: src/web/tests/screenshots/
        retention-days: 30

  report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    needs: [test, smoke-test, mobile-test]
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          artifacts/**/results.xml

    - name: Comment PR with test results
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const reportPath = 'artifacts/playwright-report-chromium/index.html';

          if (fs.existsSync(reportPath)) {
            const comment = `## 🎭 Playwright Test Results

            Test reports are available in the workflow artifacts.

            Download the \`playwright-report-*\` artifacts to view detailed results.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          }
